Fix

diff --git a/Telescope-Pi/DEBIAN/postinst b/Telescope-Pi/DEBIAN/postinst
--- a/Telescope-Pi/DEBIAN/postinst
+++ b/Telescope-Pi/DEBIAN/postinst
@@ -1,4 +1,11 @@
 #!/bin/bash
+name="$(whiptail --title "Telescope-Pi" --backtitle "By marcocipriani01" --inputbox "Enter a hostname for this device:" 8 70 3>&1 1>&2 2>&3)"
+if [[ -z "$name" ]]; then
+    echo "Error!"
+    exit 1
+fi
+ch-hostname "$name"
+
 ln -sf /lib/systemd/resolv.conf /etc/resolv.conf
 /etc/init.d/networking restart
 
@@ -15,16 +22,6 @@ fi
 sed -i 's#AutoEnable=false#AutoEnable=true#g' /etc/bluetooth/main.conf
 usermod -aG bluetooth "$USER"
 newgrp bluetooth
-cp /usr/share/Telescope-Pi/var-run-sdp.path /etc/systemd/system/var-run-sdp.path
-cp /usr/share/Telescope-Pi/var-run-sdp.service /etc/systemd/system/var-run-sdp.service
-systemctl daemon-reload
-systemctl enable bluetooth
-systemctl enable var-run-sdp.path
-systemctl enable var-run-sdp.service
-systemctl start var-run-sdp.path
-systemctl start bluetooth
-rfkill unblock bluetooth
-sdptool add SP
 
 interfaces=()
 while read -r line; do
@@ -45,5 +42,12 @@ echo "$interface $(hostname) $pswd" > /etc/telescope-pi
 systemctl daemon-reload
 systemctl enable ssh
 systemctl start ssh
+systemctl enable bluetooth
+systemctl enable var-run-sdp.path
+systemctl enable var-run-sdp.service
+systemctl start var-run-sdp.path
+systemctl start bluetooth
+rfkill unblock bluetooth
+sdptool add SP
 systemctl enable telescope-pi
 systemctl start telescope-pi
